<a href="https://colab.research.google.com/github/Mohamedaflal26/Car-Usability-risk-analyzer/blob/main/Car_Usability%26risk_analyzer.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.compose import ColumnTransformer
from sklearn.neighbors import KNeighborsClassifier
from sklearn.preprocessing import OneHotEncoder, LabelEncoder
from sklearn.metrics import confusion_matrix, accuracy_score

In [2]:
dataset = pd.read_csv('/content/car.csv')

In [3]:
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [4]:
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0, 1, 2, 3, 4])], remainder='passthrough',
                       sparse_threshold=0)
X = np.array(ct.fit_transform(X))

print(X)

[[0. 0. 0. ... 0. 0. 1.]
 [0. 0. 0. ... 0. 0. 1.]
 [0. 0. 0. ... 0. 0. 1.]
 ...
 [0. 1. 0. ... 1. 0. 0.]
 [0. 1. 0. ... 1. 0. 0.]
 [0. 1. 0. ... 1. 0. 0.]]


In [6]:
le = LabelEncoder()
y = le.fit_transform(y)

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

classifier = KNeighborsClassifier(n_neighbors=5, metric='minkowski')
classifier.fit(X_train, y_train)

y_pred = classifier.predict(X_test)

print(np.concatenate((y_pred.reshape(len(y_pred), 1), y_test.reshape(len(y_test), 1)), 1))


[[0 2]
 [0 2]
 [0 1]
 [0 1]
 [2 1]
 [1 0]
 [0 1]
 [2 0]
 [1 2]
 [1 2]
 [2 1]
 [1 0]
 [1 2]
 [0 1]
 [0 1]
 [0 2]
 [1 2]
 [1 2]
 [1 2]
 [0 2]
 [0 0]
 [1 0]
 [1 2]
 [1 1]
 [1 1]
 [0 2]
 [2 1]
 [1 0]
 [1 0]
 [0 2]
 [1 0]
 [1 0]
 [0 1]
 [2 0]
 [0 2]
 [0 1]
 [1 2]
 [2 1]
 [1 2]
 [2 0]
 [1 2]
 [0 2]
 [0 2]
 [0 1]
 [1 0]
 [0 2]
 [2 2]
 [1 2]
 [0 2]
 [0 1]
 [0 1]
 [0 2]
 [1 0]
 [2 1]
 [0 0]
 [0 0]
 [0 2]
 [1 0]
 [2 1]
 [0 2]
 [1 0]
 [0 2]
 [0 1]
 [0 0]
 [0 2]
 [1 0]
 [0 2]
 [1 0]
 [0 1]
 [0 0]
 [2 1]
 [0 0]
 [2 0]
 [1 0]
 [0 2]
 [0 2]
 [2 1]
 [0 2]
 [1 0]
 [0 0]
 [0 2]
 [1 2]
 [1 2]
 [0 0]
 [0 2]
 [2 1]
 [0 1]
 [0 2]
 [0 1]
 [0 1]
 [0 2]
 [1 0]
 [0 2]
 [2 1]
 [0 2]
 [0 0]
 [2 1]
 [0 2]
 [1 0]
 [1 2]
 [0 0]
 [0 2]
 [0 0]
 [0 1]
 [2 0]
 [0 2]
 [2 0]
 [2 0]
 [0 1]
 [0 0]
 [1 0]
 [0 0]
 [2 2]
 [0 2]
 [1 1]
 [1 0]
 [1 0]
 [0 2]
 [2 1]
 [1 0]
 [1 1]
 [0 1]
 [0 0]
 [0 0]
 [0 2]
 [0 1]
 [1 2]
 [1 0]
 [1 2]
 [1 1]
 [0 0]
 [0 1]
 [0 2]
 [0 1]
 [0 2]
 [1 2]
 [0 1]
 [0 1]
 [1 2]
 [0 1]
 [2 0]
 [0 2]
 [0 2]

In [7]:
cm = confusion_matrix(y_test, y_pred)
print(cm)

[[33 57 23]
 [64 12 30]
 [75 43  9]]


In [8]:
accuracy = accuracy_score(y_test, y_pred)
print(accuracy)

0.15606936416184972
